#!/usr/bin/env bash
# Configures a new ubuntu machine to respect the follwing requirements:
# installs nginx.
# nginx should listen on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Holberton School
# systemctl cannot be used to restart nginx.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo echo "Holberton School" >> /usr/share/nginx/html/index.html
sudo service nginx restart
