#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
new_config="\trewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
server="0,/server\s+\{/s//& \n"
sed -i -E "${server}${new_config}/" /etc/nginx/sites-enabled/default
service nginx restart
